### ISSUE TITLE
关于目录部分无法渲染的问题

### ISSUE THREAD

**Issue by MinJoker** [TonyCrane/mkdocs-heti-plugin#1]
问题描述：
装载的 mkdocs-heti-plugin 插件似乎无法渲染网站左边与右边的目录栏。

---

补充 01：
有点奇怪，我的个人笔记网站和您的个人笔记网站的目录栏都渲染失败了，但是辅学的网站渲染成功了。这里分别列举三篇文章，请关注它们的目录栏中英混排间隔：

- [我的笔记网站](https://minjoker.github.io/cs/digital_logic/note0/)
- [您的笔记网站](https://note.tonycrane.cc/sec/vulns/log4j/)
- [辅学网站](https://ckc-agc.bowling233.top/programming_lecture/lecture1/pre_class/)

---

补充 02：
于是我尝试控制变量，发现取消网站的自定义字体（JetBrains Mono，LXGW WenKai Screen，这两款字体我和您采用了一样的来源，即您的 cdn）可以使 heti “几乎”正确渲染目录栏。

为什么是几乎，因为即使如此，如果目录中对应的小标题没手打空格，那么目录栏中仍然会渲染失败，而按理说应该自动补上空格并渲染（此时目录对应的小标题就是这样渲染成功了）。

**Comment by TonyCrane** [comment]
呃 是全部没处理吧，因为我本身代码写的就是默认处理 .article 这个 selector 选到的内容也就是只有文章本身。

至于为什么你看辅学网站和换了字体会认为它们已经处理了，是因为这些情况下都英文字体是比例字体，它们的空格本身就比较窄，你如果仔细对比就能发现这里都间隔和正文里的间隔还是不一样的。而加了 JB mono 自定义字体后因为它是等宽字体，所以空格宽度和一个英文字母宽度是一样的，你看着就会很宽。

那至于为什么不处理 nav，没记错的话一部分原因是这部分样式用了 flex 来搞两侧对齐，这个一定要保证之后两个元素（否则元素就会平均分配占满一行），而 heti 的处理原理是增加 span 来标记修改的空格，这势必会导致原来只占一个元素的文章标题被切断成多个元素，显示数据有问题的。

**Comment by MinJoker** [comment]
好滴谢谢~ 是我欠考虑啦~
